#!/usr/bin/env python3
"""The web pages show a visible "page updated" stamp (web/version.js,
regenerated by `make webstamp`). This check fails when web/ content was
committed more recently than the stamp, so the stamp cannot silently go
stale -- the same catch-consistency-drift-with-a-test policy as the
bibliography and build-target checks."""
import os
import subprocess
import sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)

if not os.path.exists('web/version.js'):
    print('WEB VERSION CHECK FAILED: web/version.js missing (run make webstamp)')
    sys.exit(1)


def last_commit_time(*pathspecs):
    out = subprocess.run(['git', 'log', '-1', '--format=%ct', '--'] +
                         list(pathspecs), capture_output=True, text=True)
    s = out.stdout.strip()
    return int(s) if s else 0


try:
    content = last_commit_time('web', ':(exclude)web/version.js')
    stamp = last_commit_time('web/version.js')
    dirty = subprocess.run(
        ['git', 'status', '--porcelain', '--', 'web/version.js'],
        capture_output=True, text=True).stdout.strip() != ''
except FileNotFoundError:
    print('web version check skipped (git not available)')
    sys.exit(0)

if dirty:
    # stamp regenerated but not yet committed: compare working-tree ages
    vs = os.path.getmtime('web/version.js')
    newest = max(os.path.getmtime(os.path.join('web', f))
                 for f in os.listdir('web') if f != 'version.js')
    if newest > vs + 1:
        print('WEB VERSION CHECK FAILED: web/ files edited after the '
              'uncommitted stamp -- rerun `make webstamp`')
        sys.exit(1)
    print('web version stamp ok (uncommitted stamp newer than web files)')
    sys.exit(0)

if content > stamp:
    print('WEB VERSION CHECK FAILED: web/ content is committed newer than '
          'web/version.js -- run `make webstamp` and commit the new stamp')
    sys.exit(1)
print('web version stamp ok (stamp commit >= latest web content commit)')
