#include <string.h>

#include "mv/core.h"
#include "mv/pattern.h"

/* Shipped M-array: generated by seeded search (seed 20260803), verified:
 * all 112 4x4 windows unique under all 4 rotations, min pairwise Hamming
 * distance 2 among the 448 rotated codes. Do not edit: changing any bit
 * invalidates the spec version. */
static const unsigned char MARR[MV_PAT_GRID_ROWS][MV_PAT_GRID_COLS] = {
    { 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1 },
    { 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1 },
    { 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1 },
    { 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0 },
    { 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1 },
    { 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1 },
    { 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1 },
    { 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1 },
    { 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0 },
    { 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1 }
};

int mv_marray_bit(int col, int row)
{
    return MARR[row][col];
}

static unsigned win_code(int c0, int r0)
{
    unsigned code = 0;
    int r, c;
    for (r = 0; r < MV_PAT_WIN; r++)
        for (c = 0; c < MV_PAT_WIN; c++)
            code = (code << 1) | MARR[r0 + r][c0 + c];
    return code;
}

/* rotate a 4x4 bit block 90 degrees clockwise */
static unsigned rot90(unsigned code)
{
    unsigned out = 0;
    int r, c;
    for (r = 0; r < 4; r++)
        for (c = 0; c < 4; c++) {
            int src = (code >> (15 - ((3 - c) * 4 + r))) & 1u;
            out = (out << 1) | (unsigned)src;
        }
    return out;
}

int mv_marray_lookup(unsigned code, int *col, int *row, int *rot)
{
    int r0, c0, k;
    for (k = 0; k < 4; k++) {
        for (r0 = 0; r0 <= MV_PAT_GRID_ROWS - MV_PAT_WIN; r0++)
            for (c0 = 0; c0 <= MV_PAT_GRID_COLS - MV_PAT_WIN; c0++)
                if (win_code(c0, r0) == code) {
                    *col = c0;
                    *row = r0;
                    *rot = k;
                    return MV_OK;
                }
        code = rot90(code); /* unrotate observation by trying rotations */
    }
    return MV_ERR;
}

static unsigned gray_encode(unsigned v)
{
    return v ^ (v >> 1);
}

static void fill(unsigned char *img, int x0, int y0, int w, int h,
                 unsigned char v)
{
    int x, y;
    for (y = y0; y < y0 + h; y++)
        for (x = x0; x < x0 + w; x++)
            img[y * MV_PAT_W + x] = v;
}

/* phase patches: P1-P4 toggle every frame, P5 every 2nd frame */
static const int PATCH_XY[5][2] = {
    { 912, 32 }, { 1792, 32 }, { 32, 472 }, { 1792, 472 }, { 32, 860 }
};

void mv_pattern_render(unsigned char *img, unsigned counter)
{
    int i, j, c, r;

    memset(img, 255, (size_t)MV_PAT_W * MV_PAT_H);

    /* version block: [1,0] marker + 8 Gray bits, cells 48 px at (32,32) */
    {
        unsigned bits = (1u << 9) | (0u << 8)
                      | (gray_encode(MV_PAT_SPEC_VERSION) & 0xffu);
        for (c = 0; c < 10; c++)
            fill(img, 32 + 48 * c, 32, 48, 48,
                 (bits >> (9 - c)) & 1u ? 0 : 255);
    }

    /* nested fine grid: 3x3 cells of 40 px at (560,32) */
    for (r = 0; r < 3; r++)
        for (c = 0; c < 3; c++)
            if ((r + c) % 2 == 0)
                fill(img, 560 + 40 * c, 32 + 40 * r, 40, 40, 0);

    /* phase patches */
    for (i = 0; i < 5; i++) {
        unsigned on = (i < 4) ? (counter & 1u) : ((counter >> 1) & 1u);
        fill(img, PATCH_XY[i][0], PATCH_XY[i][1], 96, 96, on ? 0 : 255);
    }

    /* saddle grid + M-array dots */
    for (r = 0; r < MV_PAT_GRID_ROWS; r++)
        for (c = 0; c < MV_PAT_GRID_COLS; c++) {
            int x0 = MV_PAT_GRID_X0 + MV_PAT_CELL * c;
            int y0 = MV_PAT_GRID_Y0 + MV_PAT_CELL * r;
            int black = ((r + c) % 2 == 0);
            if (black)
                fill(img, x0, y0, MV_PAT_CELL, MV_PAT_CELL, 0);
            if (mv_marray_bit(c, r)) {
                int d0 = (MV_PAT_CELL - MV_PAT_DOT) / 2;
                fill(img, x0 + d0, y0 + d0, MV_PAT_DOT, MV_PAT_DOT,
                     black ? 255 : 0);
            }
        }

    /* counter strip: [1,0] + 20 Gray bits + parity + ~parity */
    {
        unsigned g = gray_encode(counter & ((1u << MV_PAT_CTR_BITS) - 1u));
        unsigned parity = 0, bits[MV_PAT_CTR_CELLS];
        for (j = 0; j < MV_PAT_CTR_BITS; j++)
            parity ^= (g >> j) & 1u;
        bits[0] = 1;
        bits[1] = 0;
        for (j = 0; j < MV_PAT_CTR_BITS; j++)
            bits[2 + j] = (g >> (MV_PAT_CTR_BITS - 1 - j)) & 1u;
        bits[22] = parity;
        bits[23] = !parity;
        for (c = 0; c < MV_PAT_CTR_CELLS; c++)
            fill(img, MV_PAT_CTR_X0 + MV_PAT_CTR_CELL * c, MV_PAT_CTR_Y0,
                 MV_PAT_CTR_CELL, MV_PAT_CTR_CELL, bits[c] ? 0 : 255);
    }
}

void mv_pattern_corner_px(int i, int j, double xy[2])
{
    xy[0] = MV_PAT_GRID_X0 + MV_PAT_CELL * (i + 1);
    xy[1] = MV_PAT_GRID_Y0 + MV_PAT_CELL * (j + 1);
}

void mv_pattern_ctr_cell_px(int c, double xy[2])
{
    xy[0] = MV_PAT_CTR_X0 + MV_PAT_CTR_CELL * c + MV_PAT_CTR_CELL / 2.0;
    xy[1] = MV_PAT_CTR_Y0 + MV_PAT_CTR_CELL / 2.0;
}

void mv_pattern_patch_px(int i, double xy[2])
{
    xy[0] = PATCH_XY[i][0] + MV_PAT_PATCH / 2.0;
    xy[1] = PATCH_XY[i][1] + MV_PAT_PATCH / 2.0;
}

void mv_pattern_version_cell_px(int c, double xy[2])
{
    xy[0] = MV_PAT_VER_X0 + MV_PAT_VER_CELL * c + MV_PAT_VER_CELL / 2.0;
    xy[1] = MV_PAT_VER_Y0 + MV_PAT_VER_CELL / 2.0;
}

/* ---- coarse tier (spec v2) ---------------------------------------- */

int mv_pattern2_mark(int col, int row)
{
    return (row == 0 && (col == 0 || col == 1)) || (row == 1 && col == 0);
}

void mv_pattern2_render(unsigned char *img, unsigned counter)
{
    int r, c, j;
    memset(img, 255, (size_t)MV_PAT_W * MV_PAT_H);
    for (r = 0; r < MV_PAT2_GRID_ROWS; r++)
        for (c = 0; c < MV_PAT2_GRID_COLS; c++) {
            int x0 = MV_PAT2_GRID_X0 + MV_PAT2_CELL * c;
            int y0 = MV_PAT2_GRID_Y0 + MV_PAT2_CELL * r;
            int black = ((r + c) % 2 == 0);
            if (black)
                fill(img, x0, y0, MV_PAT2_CELL, MV_PAT2_CELL, 0);
            if (mv_pattern2_mark(c, r)) {
                int d0 = (MV_PAT2_CELL - MV_PAT2_MARK) / 2;
                fill(img, x0 + d0, y0 + d0, MV_PAT2_MARK, MV_PAT2_MARK,
                     black ? 255 : 0);
            }
        }
    {
        unsigned g = gray_encode(counter & ((1u << MV_PAT2_CTR_BITS) - 1u));
        unsigned parity = 0, bits[MV_PAT2_CTR_CELLS];
        for (j = 0; j < MV_PAT2_CTR_BITS; j++)
            parity ^= (g >> j) & 1u;
        bits[0] = 1;
        bits[1] = 0;
        for (j = 0; j < MV_PAT2_CTR_BITS; j++)
            bits[2 + j] = (g >> (MV_PAT2_CTR_BITS - 1 - j)) & 1u;
        bits[10] = parity;
        bits[11] = !parity;
        /* bits render as ISOLATED squares in white gutters: adjacent
         * solid cells of opposite color would create saddle-like
         * responses that pollute the corner lattice; isolated
         * rectangles make only L-corners, which the detector's
         * threshold rejects */
        for (c = 0; c < MV_PAT2_CTR_CELLS; c++)
            if (bits[c])
                fill(img,
                     MV_PAT2_CTR_X0 + MV_PAT2_CTR_CELL * c
                         + (MV_PAT2_CTR_CELL - MV_PAT2_MARK) / 2,
                     MV_PAT2_CTR_Y0, MV_PAT2_MARK, MV_PAT2_CTR_H, 0);
    }
}

void mv_pattern2_corner_px(int i, int j, double xy[2])
{
    xy[0] = MV_PAT2_GRID_X0 + MV_PAT2_CELL * (i + 1);
    xy[1] = MV_PAT2_GRID_Y0 + MV_PAT2_CELL * (j + 1);
}

static int hamming(unsigned a, unsigned b)
{
    unsigned x = a ^ b;
    int n = 0;
    while (x) {
        n += (int)(x & 1u);
        x >>= 1;
    }
    return n;
}

int mv_pattern_selftest(void)
{
    enum { NW = (MV_PAT_GRID_COLS - 3) * (MV_PAT_GRID_ROWS - 3) };
    unsigned codes[NW * 4];
    int n = 0, r0, c0, k, i, j;
    for (r0 = 0; r0 <= MV_PAT_GRID_ROWS - MV_PAT_WIN; r0++)
        for (c0 = 0; c0 <= MV_PAT_GRID_COLS - MV_PAT_WIN; c0++) {
            unsigned w = win_code(c0, r0);
            for (k = 0; k < 4; k++) {
                codes[n++] = w;
                w = rot90(w);
            }
        }
    for (i = 0; i < n; i++)
        for (j = i + 1; j < n; j++)
            if (hamming(codes[i], codes[j]) < 2)
                return MV_ERR;
    return MV_OK;
}
